### ISSUE TITLE
otherUsername in History

### ISSUE THREAD

**Issue by mrschtief** [immopoly/appengine#10]
wir haben ja darüber gesprochen, dass es möglich sein soll das öffentliche Profil eines anderen Benutzers einzusehen, wenn
ich versucht habe seine Wohnung zu übernehmen oder umgekehrt.

Es kommen also zwei Typen von Historieneinträgen in Frage:
TYPE_EXPOSE_MONOPOLY_POSITIVE 3
TYPE_EXPOSE_MONOPOLY_NEGATIVE 4

Für den Type 3 ist es einfach, der Text immer mit "<USER> wollte deine Wohnung übernehmen.".
Erstes Wort = Username.

Für Type 4 ist es nicht so ganz so einfach. "Die Wohnung '<WOHUNG> gehört schon '<USER>' Strafe...".
Letztes Wort in einfachen Hochkomma = Username.

So richtig gut gefällt es mir aber nicht, den Benutzernamen auf diese Art und Weise aus den Historientexten herauszuholen.
Können wir das Objekt nicht analog zur exposeId um den Benutzernamen erweitern?

**Comment by mrschtief** [comment]
ist als otherUsername in der History

**Comment by tobiasheine** [comment]
Klappt aber nur für neue Einträge, richtig?

**Comment by mrschtief** [comment]
richtig, bei alten habe ich die info noch nicht.

2012/1/25 tobiasheine
reply@reply.github.com:
