### ISSUE TITLE
/user/history leer wenn keine weitere vorhanden

### ISSUE THREAD

**Issue by mrschtief** [immopoly/appengine#11]
so lange die momentane version im itunes ist, geben wir eine leere liste statt einer exception zurück.... umgehend ändern wenn itunes upgedatet

**Comment by tobiasheine** [comment]
Habe ich getestet. Fehler tritt nun in der store version nicht mehr auf.

**Comment by mrschtief** [comment]
ok ich lass den offen bis ihr die neue version im itunes habt

On Wed, Jan 25, 2012 at 11:00 AM, tobiasheine
reply@reply.github.com
wrote:
