### ISSUE TITLE
c2dm NotRegistered

### ISSUE THREAD

**Issue by mrschtief** [immopoly/appengine#12]
mal schauen ob das ok so ist

2012-01-26 21:27:09.641
org.immopoly.appengine.ImmopolyC2DMMessaging sendNoRetry: Got updated auth token from datamessaging servers: DQAAAM8AAAAj39_ZptPdSNJFzuoEH_GR8UZdAYiNJGGmKP0QgPr9sLLtnO9LpOUkK2EENMKOef4_s0L_3hTWsKjbmtIgCiyzT34LuETi8jVQ6XIsjqGYFDp1zCmAQaDEp3oH-DCzBn6FixDILcxY7_kGmLpo3NwU8JCL18jQKxNP-Bkt55hNiGamehXifGWCATVn3twQpFv9AW8psLOsCdQLjoP8jEJISuogVq1C5IKBcljhTaoSsEZuVU0Ypgi0FKoEBsjdx8IT6nWUkga1cffgIC1A4Bxm
W 2012-01-26 21:27:09.641
org.immopoly.appengine.ImmopolyC2DMMessaging sendNoRetry: Got error response from Google datamessaging endpoint: NotRegistered
E 2012-01-26 21:27:09.641
org.immopoly.appengine.ExposeCronjobServlet doGet: Send c2dm message toLionKingImmo FAILED 
java.io.IOException: NotRegistered
    at org.immopoly.appengine.ImmopolyC2DMMessaging.sendNoRetry(ImmopolyC2DMMessaging.java:132)
    at org.immopoly.appengine.ExposeCronjobServlet.doGet(ExposeCronjobServlet.java:115)

**Comment by keyboardsurfer** [comment]
C2DM ist tot, lang lebe GCM.
