### ISSUE TITLE
Teilnahmebedingungen IS24 Challenge

### ISSUE THREAD

**Issue by mrschtief** [immopoly/appengine#22]
verschicken wir an alle ersten 500 und an alle neu angemeldeten eine email von immopolyteam@gmail.com mit einem Text (welchen?) und mit einem Link auf die TNB, die wir auf immopoly.org packen?

Wer nicht antwortet, der bestätigt? oder soll ich einen link in die Mail packen wo der aktuelle Token des users drin ist und wenn man drauf klickt, dann setze ich nen boolean im user object auf true?

**Comment by mrschtief** [comment]
Hallo Immopoly Spieler :****

Wir machen zusammen mit Immobilienscout 24 eine Release TesterKampangne.
Wenn du daran battelst du zusammen mit den anderen release testern um
tolle preise.

die teilnahme bedingungen stehen unter .... (link zur is24 version von
(TNB_Immopoly.doc))

wenn du mit bestaetige hier -> link inclusive hash

**Comment by yncyrydybyl** [comment]
die tnb befinden sich unter: http://www.static-immobilienscout24.de/MungoBlobs/2012/03/19/180528_Immopoly.pdf
