### ISSUE TITLE
falscher Titel in Historie bei übernahme

### ISSUE THREAD

**Issue by mrschtief** [immopoly/appengine#25]
In der Historie steht der falsche Titel, 

elbart  vor 5 Minuten  
Strafe: 46.20 Eur

Die Wohnung 'TOP-LAGE! Schöne und ruhige 3-Zimmerwohnung im Winsviertel in Prenzlauer Berg zu vermieten.' gehört schon 'Wurstladen'

folgendes expose wurde aber gemeint.... 

http://www.immobilienscout24.de/expose/63772827

was ist da los?

**Comment by keyboardsurfer** [comment]
Kann aus historischen Gründen nicht mehr nachvollzogen werden.
