### ISSUE TITLE
heatmap user

### ISSUE THREAD

**Issue by mrschtief** [immopoly/appengine#28]
einaml täglich werden bei der nächtlichen berechnung des users seine aktuellen wohnungen geografisch geclustert (auflösung 1km mit geofuzzing) die cluster werden gewichtet und abgespeichert und können dann über die heatmap api abgefragt werden

/statistic/heatmap?type=user&userId=xyz

**Comment by stefanhoth** [comment]
Geil! Genau das wollte ich vorschlagen. Optional wäre natürlich eine Liste aller jemals betreuten Wohnungen zu sehen, aber dann müssten wir die Location zwischenspeichern.

**Comment by mrschtief** [comment]
jepp mache das grade optional um nicht zuviel zu verraten kann ich jetzt auch die letzten 50 vermieteten wohnungen nehmen. und ja wir speichern alle exposes auch die vermieteten mit location eines users..... bitgable my ass

**Comment by keyboardsurfer** [comment]
waiting for #15
