### ISSUE TITLE
404 bei falschem Userprofil 

### ISSUE THREAD

**Issue by stefanhoth** [immopoly/appengine#35]
Beim Aufruf eines Userprofils mit nicht existentem Username hätte ich gern statt 200 OK lieber ein 404 Not Found als HTTP-Response-Code.

http://immopoly.appspot.com/user/profile/idontexists.json

Danke.

**Comment by mrschtief** [comment]
Kann ich leider nicht machen, da die apps momentan die exception parsen und
wenn ich jetzt bei exception 404 funzt erstmal nichts mehr ..... sorry
Am 30.03.2012 23:19 schrieb "Stefan Hoth" <
reply@reply.github.com

**Comment by stefanhoth** [comment]
Ok. Aber die 404 könnte ja weiter die Exception enthalten - nur eben mit anderem Statuscode.

Wir müssen mal bei den Clients nachfragen, ob sie auf 200 OK checken.

**Comment by mrschtief** [comment]
Naja ne 404 macht doch ne exception in java connection framework, oder
irrre ich grade?
Am 30.03.2012 23:25 schrieb "Stefan Hoth" <
reply@reply.github.com

**Comment by stefanhoth** [comment]
Ich glaube nicht zwangsläufig. Wenn man mit HTTPClient arbeitet kann man auch mit einer 404-Response umgehen ohne exception catchen zu müssen. Ich find nur auf die Schnelle im Android nicht, wo mit der AppEngine geredet wird. Dann könnte man das sehen. Naja, egal, machs ruhig zu, wäre ideal gewesen, aber muss nich sein.
